version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '7000:3000'
    env_file:
      - .env
    depends_on:
      - mongo
    networks:
      - super-net

  mongo:
    image: mongo:6
    ports:
      - '27018:27017' 
    volumes:
      - mongo-data:/data/db
    networks:
      - super-net

networks:
  super-net:
    driver: bridge
volumes:
  mongo-data:
