services:
  super-app:
    image: node
    depends_on:
      - super-postgres-db
      - super-mongo-db
  super-postgres-db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5436:5432'
    networks:
      - super-postgres-net
  super-mongo-db:
    image: mongo
    environment:
      - name=value
    ports:
      - '24121:27017'
    networks:
      - super-mongo-net
networks:
  super-postgres-net:
    driver: bridge
  super-mongo-net:
    driver: bridge